services:
  grav:
    container_name: grav
    restart: unless-stopped
    image: lscr.io/linuxserver/grav:1.8.0
    ports:
      - 8161:80
    volumes:
      - {{CONFIG}}/grav/grav-comfig:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{TZ}}
