services:
  bitcoind:
    container_name: bitcoind
    image: docker.io/lncm/bitcoind:v28.0
    user: 0:0
    volumes:
      - {{CONFIG}}/bitcoind:/root/.bitcoin
    ports:
      - 8333:8333
      - 8332:8332
      - 28332:28332
      - 28333:28333
    restart: unless-stopped
    stop_grace_period: 15m30s
    command: >-
      -dbcache=${BITCOIND_DB_CACHE:-450}
      -maxmempool=${BITCOIND_MAX_MEMPOOL:-300}
      -listen=${BITCOIND_LISTEN:-1}
      -server=${BITCOIND_SERVER:-1}
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -prune=${BITCOIND_PRUNING:-0}
      -maxconnections=${BITCOIND_MAXPEERS:-125}
      -txindex=${BITCOIND_TXINDEX:-1}
      -peerbloomfilters=${BITCOIND_BLOOM_FILTERS:-1}
      -blockfilterindex=${BITCOIND_BLOCK_FILTER:-1}
      -peerblockfilters=${BITCOIND_BLOCK_FILTER:-1}