services:
  docmost:
    container_name: docmost
    image: docker.io/docmost/docmost:0.25.3
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      - APP_URL=http://localhost
      - APP_SECRET=${DOCMOST_APP_SECRET}
      - DATABASE_URL=postgresql://docmost:${DOCMOST_PG_PASSWORD}@docmost-db:5432/docmost?schema=public
      - REDIS_URL=redis://docmost-redis:6379
    ports:
      - 9713:3000
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/docmost/storage:/app/data/storage
  docmost-db:
    container_name: docmost-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=docmost
      - POSTGRES_USER=docmost
      - POSTGRES_PASSWORD=${DOCMOST_PG_PASSWORD}
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/docmost/postgresql:/var/lib/postgresql/data
  docmost-redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/docmost/redis:/data
