services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.5
    container_name: open-webui
    volumes:
      - {{CONFIG}}/open-webui:/app/backend/data
    ports:
      - 8536:8080
    environment:
      - OLLAMA_BASE_URL=${OPENWEBUI_OLLAMA_URL}
      - OPENAI_API_KEY=${OPENWEBUI_OPENAI_KEY}
    restart: unless-stopped
