services:
  tandoor:
    container_name: tandoor
    image: ghcr.io/tandoorrecipes/recipes:2.5.3
    volumes:
      - {{CONFIG}}/tandoor/staticfiles:/opt/recipes/staticfiles
      - {{CONFIG}}/tandoor/mediafiles:/opt/recipes/mediafiles
    ports:
      - 8341:80
    environment:
      - SECRET_KEY=${TANDOOR_SECRET_KEY}
      - DB_ENGINE=django.db.backends.postgresql
      - GUNICORN_MEDIA=1
      - POSTGRES_HOST=tandoor-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tandoor
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRESS_PASSWORD}
      - POSTGRES_DB=tandoordb
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      tandoor-db:
        condition: service_healthy
  tandoor-db:
    image: postgres:15-alpine
    container_name: tandoor-db
    volumes:
      - {{CONFIG}}/tandoor/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tandoor
      - POSTGRES_PASSWORD=${TANDOOR_POSTGRESS_PASSWORD}
      - POSTGRES_DB=tandoordb
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - '-U'
        - $$POSTGRES_USER
        - '-d'
        - $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
