services:
  flowise:
    image: docker.io/flowiseai/flowise:3.0.13
    restart: unless-stopped
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    container_name: flowise
    environment:
      - PORT=8009
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
    ports:
      - 8009:8009
    volumes:
      - {{CONFIG}}/flowise/flowise:/root/.flowise
