services:
  wordpress:
    container_name: wordpress
    image: wordpress:6.9.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - {{CONFIG}}/wordpress/wordpress:/var/www/html
    ports:
      - 8213:80
    restart: unless-stopped
    depends_on:
      - wordpress-db
  wordpress-db:
    container_name: wordpress-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - {{CONFIG}}/wordpress/mariadb:/var/lib/mysql
    restart: unless-stopped
