services:
  rss:
    image: codeberg.org/danb/rss:v1.6.5
    container_name: rss
    environment:
      - APP_NAME=Tipi-RSS
      - APP_FEED_UPDATE_FREQUENCY=35
      - APP_LOAD_POST_THUMBNAILS=true
    volumes:
      - {{CONFIG}}/rss/storage:/app/storage
    ports:
      - 8141:80
    restart: unless-stopped
