services:
  siyuan:
    image: docker.io/b3log/siyuan:v3.5.8
    container_name: siyuan
    command:
      - '--workspace=/siyuan/workspace/'
      - '--accessAuthCode=${SIYUAN_ACCESS_AUTH_CODE}'
    user: '1000:1000'
    restart: unless-stopped
    environment:
      - TZ={{TZ}}
      - PUID=1000
      - PGID=1000
    volumes:
      - {{CONFIG}}/siyuan/workspace:/siyuan/workspace/
    ports:
      - 6806:6806
