services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:3.1.0
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{TZ}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{CONFIG}}/lidarr:/config
      - {{MEDIA}}:/media
    ports:
      - 8131:8686
    restart: unless-stopped
