services:
  grocy:
    image: lscr.io/linuxserver/grocy:v4.0.3-ls215
    container_name: grocy
    volumes:
      - {{CONFIG}}/grocy:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{TZ}}
    ports:
      - 8136:80