#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Gulf >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Gulf=/luci-static/gulf
		set luci.main.mediaurlbase=/luci-static/gulf
		commit luci
	EOF
fi

exit 0
