services:
  nextcloud-mini:
    container_name: nextcloud-mini
    image: nextcloud:30-apache
    restart: unless-stopped
    ports:
      - 8564:80
    volumes:
      - {{CONFIG}}/nextcloud-mini/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-mini-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_MINI_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_MINI_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_MINI_ADMIN_USER}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_MINI_TRUSTED_DOMAINS}
  nextcloud-mini-db:
    container_name: nextcloud-mini-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/nextcloud-mini/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_MINI_DB_PASSWORD}