services:
  homer:
    image: docker.io/b4bz/homer:v25.11.1
    container_name: homer
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/homer:/www/assets
    ports:
      - 8562:8080
