services:
  metabase:
    container_name: metabase
    image: docker.io/metabase/metabase:v0.58.7
    restart: unless-stopped
    ports:
      - 8680:3000
    environment:
      - MGID=${GID-1000}
      - MB_DB_FILE=/metabase-data/metabase.db
      - JAVA_TIMEZONE={{TZ}}
    volumes:
      - {{CONFIG}}/metabase/metabase/data:/metabase-data
      - {{CONFIG}}/metabase/metabase/plugins:/plugins
