services:
  gotify:
    image: docker.io/gotify/server:2.9.0
    container_name: gotify
    restart: unless-stopped
    volumes:
      - {{CONFIG}}/gotify:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    ports:
      - 8129:80
